### PR TITLE
Added $unset aggregation pipeline stage

### PR DESCRIPTION
**Pull request by markbigler**
PR for https://github.com/bwaldvogel/mongo-java-server/issues/118

@bwaldvogel: I don't have a MongoDB 4.2 installed on this device. Could you please add the missing validation error codes (marked with FIXME) and maybe also some kind of integration tests?

BR, Mark

### CODE REVIEW

**Comment by markbigler** [comment]
Added aggregation backend test for $unset (and fixed the 🐞 found with it).

**Comment by markbigler** [comment]
RealEmbeddedMongoAggregationTest is failing because it uses MongoDB 4.0 and [$unset ](https://docs.mongodb.com/manual/reference/operator/aggregation/unset/) is new in version 4.2.

@bwaldvogel: It looks like embedded mongodb does not support v4.2 yet 😡 (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/295). How are we gonna handle this?

**Comment by bwaldvogel** [comment]
@markbigler: I’ll have a look if we can switch to testcontainers…

**Comment by bwaldvogel** [comment]
I was able to switch to testcontainers and run the `RealMongoBackendTest` with MongoDB 4.2.3.

So I could finally merge this PR and also implement the FIXMEs.
@markbigler: Thanks for this nice contribution!

**Pull request merged**
