### PR TITLE
Partial support of $redact aggregation stage (without $$DESCEND outcome)

### PR DESCRIPTION
**Pull request by belas89**

### CODE REVIEW

**Comment by bwaldvogel** [comment]
Thanks for this contribution!

**Comment by belas89** [comment]
Hi,
Could you please share your plans about nearest release day? :)

**Comment by bwaldvogel** [comment]
My current plan is to release a new version within the next week. I would like to include https://github.com/bwaldvogel/mongo-java-server/pull/131.

**Comment by bwaldvogel** [comment]
Version `1.28.0` is available now

**Pull request merged**
