### PR TITLE
Add support for nested fields in $lookup stage

### PR DESCRIPTION
**Pull request by markbigler**
A pipeline with a $lookup on a nested field is currently not working. With this PR the needed functionality will be added.

### CODE REVIEW

**Comment by markbigler** [comment]
I'm a bit confused and can't reproduce the problem. I successfully ran the tests before the switch to JUnit 5 (https://github.com/bwaldvogel/mongo-java-server/commit/07666346a2b5910083a42a2fe37a929e415abd98). With the latests version I face the following issue:

```
java.lang.NoClassDefFoundError: org/junit/platform/commons/util/Preconditions
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:83)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:67)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:370)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:365)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:309)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:224)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:208)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.util.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

**Comment by markbigler** [comment]
Updating to eclipse 2019-12 and adding `prepareAuthorsCollectionMock()` to the failing test resolved the issue 🎉

**Comment by iRodneyS** [comment]
I face the same problems running aggregation with multiple lookup and unwind stages. The unwinded nested document can't be referenced in a following lookup. With  Mark's fix it works fine. FänX

**Comment by bwaldvogel** [comment]
@markbigler, thanks for your contribution, again :smiley:

**Comment by bwaldvogel** [comment]
Your PR is part of `v1.26.0`

**Pull request merged**
