### PR TITLE
Added positional $ operator (projection)

### PR DESCRIPTION
**Pull request by markbigler**
Hi @bwaldvogel 

As missed in #104, I have added the positional $ projection operator - hope this works :smirk:

Best regards,
Mark

### CODE REVIEW

**Comment by markbigler** [comment]
Sorry for mixing several features in a single PR :innocent:

**Comment by bwaldvogel** [comment]
Thanks for this contribution!

**Comment by Maxeh** [comment]
@markbigler Thank you for the fix ;)

**Comment by bwaldvogel** [comment]
I’ve just released version `1.23.0` that contains this fix

**Pull request merged**
